architecture:
  version: 0.3
  subtree:
    - name: system
      local:
        - name: DRAM
          class: DRAM
          attributes:
            type: LPDDR4
            block-size: 16
            word-bits: 8
      subtree:
        - name: HLSCNN
          attributes:
            technology: 45nm
          local:
            - name: DummyBuffer
              class: regfile
              attributes:
                depth: 16
                width: 128
                word-bits: 8
                block-size: 16
          subtree:
          - name: PE
            local:
              - name: Resigsters-Input
                class: regfile
                attributes:
                  entries: 32768
                  block-size: 16
                  word-bits: 8
                  meshX: 1
                  read_bandwidth: 16
                  write_bandwidth: 16
              - name: Resigsters-Weight
                class: regfile
                attributes:
                  entries: 262144
                  block-size: 8
                  word-bits: 16
                  meshX: 1
                  read_bandwidth: 8
                  write_bandwidth: 8
              - name: Resigsters-Output
                class: regfile
                attributes:
                  entries: 32768
                  block-size: 8
                  word-bits: 16
                  meshX: 1
                  read_bandwidth: 8
                  write_bandwidth: 8
              - name: mac
                class: intmac
                attributes:
                  datawidth: 16
                  meshX : 1

architecture_constraints:
  targets:
    - target: Resigsters-Weight
      type: bypass
      bypass: [Inputs, Outputs]
      keep: [Weights]
    - target: Resigsters-Input
      type: bypass
      bypass: [Weights, Outputs]
      keep: [Inputs]
    - target: Resigsters-Output
      type: bypass
      bypass: [Inputs, Weights]
      keep: [Outputs]
    - target: DummyBuffer
      type: bypass
      bypass: [Inputs, Outputs, Weights]

    - target: DRAM
      type: temporal
    - target: Resigsters-Weight
      type: temporal
      factors: M1
    - target: Resigsters-Input
      type: temporal
      factors: N1
    - target: Resigsters-Output
      type: temporal
      factors: K1
    - target: DummyBuffer
      type: temporal
      factors: M1 N1 K1

mapspace_constraints:
  targets:
    - target: DummyBuffer
      type: temporal
      permutation: MNK

mapper:
  live-status : False
  num-thread: 16
  algorithm: hybrid
  optimization-metrics:
  - last-level-accesses
  search-size: 20000
  victory-condition: 1000
  timeout: 0

problem:
  instance:
    M: 256
    N: 512
    K: 1024
  shape:
    dimensions: [ M, N, K ]
    data-spaces:
      - name: Inputs
        projection:
          - [ [M] ]
          - [ [K] ]
      - name: Weights
        projection:
          - [ [N] ]
          - [ [K] ]
      - name: Outputs
        projection:
          - [ [M] ]
          - [ [N] ]
        read-write: True
    name: gemm
